"""Added account table

Revision ID: bbc1fc87614d
Revises: 
Create Date: 2021-11-18 16:39:47.055523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc1fc87614d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Audience',
    sa.Column('idAudience', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idAudience')
    )
    op.create_table('Status',
    sa.Column('idStatus', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statusName', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idStatus')
    )
    op.create_table('UserStatus',
    sa.Column('idStatus', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statusName', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idStatus')
    )
    op.create_table('User',
    sa.Column('idUser', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=45), nullable=True),
    sa.Column('firstName', sa.VARCHAR(length=45), nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=45), nullable=True),
    sa.Column('email', sa.VARCHAR(length=45), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(length=45), nullable=True),
    sa.Column('userStatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userStatus'], ['UserStatus.idStatus'], ),
    sa.PrimaryKeyConstraint('idUser')
    )
    op.create_table('Reservation',
    sa.Column('idReservation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idAudience', sa.Integer(), nullable=True),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.Column('amountOfHours', sa.Integer(), nullable=True),
    sa.Column('dateTimeOfReservation', sa.VARCHAR(length=45), nullable=True),
    sa.Column('dateTimeOfEndReservation', sa.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['idAudience'], ['Audience.idAudience'], ),
    sa.ForeignKeyConstraint(['idStatus'], ['Status.idStatus'], ),
    sa.ForeignKeyConstraint(['idUser'], ['User.idUser'], ),
    sa.PrimaryKeyConstraint('idReservation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reservation')
    op.drop_table('User')
    op.drop_table('UserStatus')
    op.drop_table('Status')
    op.drop_table('Audience')
    # ### end Alembic commands ###
